# Generated by Django 2.0.6 on 2018-06-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector_Partnerships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_title', models.CharField(max_length=200)),
                ('target_industry', models.CharField(max_length=100)),
                ('lead_applicant_organization', models.CharField(max_length=200)),
                ('lead_applicant_organization_link', models.CharField(max_length=300)),
                ('contact_name', models.CharField(max_length=100)),
                ('comprehensive_plan', models.CharField(max_length=200)),
            ],
        ),
    ]
