# Generated by Django 2.0.6 on 2018-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector_partnerships',
            name='lead_applicant_organization_link',
        ),
        migrations.AlterField(
            model_name='sector_partnerships',
            name='lead_applicant_organization',
            field=models.CharField(max_length=400),
        ),
    ]
