# Generated by Django 2.0.6 on 2018-06-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180618_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_Internships_Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.CharField(max_length=100)),
                ('activity_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employers_Served',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100)),
                ('new_hire_training', models.NullBooleanField()),
                ('incumbent_worker_training', models.NullBooleanField()),
                ('partnerships', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='High_School_Students_Completing_Internships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.CharField(max_length=100)),
                ('activity_description', models.TextField()),
                ('high_school_internships_completed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Incumbent_Worker_Training_Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.CharField(max_length=100)),
                ('description_of_training_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Incumbent_Workers_Upskilled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.CharField(max_length=100)),
                ('incumbent_workers_upskilled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry_Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='New_Career_Technial_High_School_Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.CharField(max_length=100)),
                ('CTE_progam_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='New_Hire_Training_Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.CharField(max_length=100)),
                ('description_of_training_activities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='New_Hires_Placed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.CharField(max_length=100)),
                ('new_hires_placed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance_Finances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_rate', models.CharField(max_length=10)),
                ('avreage_wage_after_placement', models.CharField(max_length=10)),
                ('avreage_wage_gain_of_incumbent_worker_trainees', models.CharField(max_length=10)),
                ('cost_per_individual', models.CharField(max_length=10)),
                ('benchmark_cost', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline_Development_Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.CharField(max_length=100)),
            ],
        ),
    ]
