# Generated by Django 2.0.6 on 2018-06-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_college_internships_completed_employers_served_high_school_students_completing_internships_incumbent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance_finances',
            old_name='avreage_wage_gain_of_incumbent_worker_trainees',
            new_name='avreage_wage_gain',
        ),
    ]
