# Generated by Django 2.0.6 on 2018-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180618_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector_partnerships',
            name='organization_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sector_partnerships',
            name='lead_applicant_organization',
            field=models.CharField(max_length=200),
        ),
    ]
