# Generated by Django 2.0.6 on 2018-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180619_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector_partnerships',
            name='organization_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector_partnerships',
            name='plan_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
