# Generated by Django 2.0.6 on 2018-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180619_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers_served',
            name='incumbent_worker_training',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employers_served',
            name='new_hire_training',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
