# Generated by Django 2.0.6 on 2018-06-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180621_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_internships_completed',
            name='college_internships_completed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
